# Generated by Django 3.0.2 on 2020-01-11 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Peliculas_Populares',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portada', models.CharField(max_length=400)),
                ('titulo', models.CharField(max_length=90)),
                ('creador', models.CharField(max_length=90)),
                ('puntaje', models.DecimalField(decimal_places=1, max_digits=2)),
                ('genero', models.CharField(max_length=50)),
                ('hora', models.IntegerField()),
                ('minutos', models.IntegerField()),
                ('descripcion', models.CharField(max_length=700)),
            ],
        ),
    ]
